import re

with open('src/App.jsx', 'r') as f:
    content = f.read()

courses_pattern = r"const DEFAULT_COURSES = \[.*?\];"
new_courses = """const DEFAULT_COURSES = [
  {
    id: 1,
    title: 'Government Exam Preparation',
    target: 'SSC, Railway, Banking, WBCS, WBPSC, Police, Defence, TET, CTET',
    duration: '6 Months',
    mode: 'Online / Offline',
    center: 'All Centers',
    price: '₹5,999',
    originalPrice: '₹9,999',
    discount: '40% OFF',
    image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=800&q=80',
    description: 'Indian government aspirants studying for SSC, Railway, Banking, WBCS, Police exams in a modern classroom setting with advanced study materials.',
    schedule: 'Morning & Evening Batches',
    faculty: 'Expert Government Officers',
    syllabus: [
      'Comprehensive Coverage of Quant & Reasoning',
      'General Awareness & Current Affairs',
      'Weekly Mock Tests',
      'Doubt Clearing Sessions'
    ],
    enrollmentFee: '₹199',
    badge: 'BESTSELLER',
    rating: 4.9,
    studentCount: '3,200',
    mentorName: 'Rajiv Sharma',
    mentorPhoto: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=100&q=80',
    language: 'English, Hindi, Bengali',
    certificate: true,
    emi: true,
    seatsLeft: 12,
    startsIn: '2 Days'
  },
  {
    id: 2,
    title: 'Interview Preparation',
    target: 'Freshers, Corporate Jobs',
    duration: '30 Days',
    mode: 'Online / Offline',
    center: 'All Centers',
    price: '₹999',
    originalPrice: '₹1,999',
    discount: '50% OFF',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
    description: 'Corporate interview, HR, Resume building and Mock Interview preparation.',
    schedule: 'Flexible Timings',
    faculty: 'Corporate HR Experts',
    syllabus: [
      'Resume Building',
      'LinkedIn Optimization',
      'Mock Interview',
      'Communication Skills & GD Practice'
    ],
    enrollmentFee: '₹199',
    badge: 'NEW',
    rating: 4.8,
    studentCount: '1,500',
    mentorName: 'Anita Desai',
    mentorPhoto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=100&q=80',
    language: 'English, Hindi',
    certificate: true,
    emi: false,
    seatsLeft: 25,
    startsIn: 'Next Week'
  },
  {
    id: 3,
    title: 'MAKAUT Semester Preparation',
    target: 'Engineering Students',
    duration: 'Per Semester',
    mode: 'Online / Offline',
    center: 'All Centers',
    price: '₹1,499',
    originalPrice: '₹2,499',
    discount: '40% OFF',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80',
    description: 'Engineering students coding with laptops on campus with books.',
    schedule: 'Weekend & Evening Batches',
    faculty: 'University Faculty & Tech Experts',
    syllabus: [
      'Semester Preparation',
      'Previous Year Questions',
      'Lab Viva Preparation',
      'Notes & Assignments'
    ],
    enrollmentFee: '₹199',
    badge: 'LIVE',
    rating: 4.7,
    studentCount: '4,100',
    mentorName: 'Dr. Amit Bose',
    mentorPhoto: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=100&q=80',
    language: 'English, Bengali',
    certificate: true,
    emi: true,
    seatsLeft: 8,
    startsIn: 'Tomorrow'
  },
  {
    id: 4,
    title: 'Board Exam Preparation',
    target: 'Class 10 & 12 Students',
    duration: 'Entire Session',
    mode: 'Online / Offline',
    center: 'All Centers',
    price: '₹1,499',
    originalPrice: '₹2,999',
    discount: '50% OFF',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80',
    description: 'Class 10 and Class 12 students in library studying with teachers.',
    schedule: 'Regular Evening Batches',
    faculty: 'Experienced School Teachers',
    syllabus: [
      'Board Exam Suggestions',
      'Mock Tests Series',
      'Chapter Notes & Revision',
      'Expected Questions Practice'
    ],
    enrollmentFee: '₹199',
    badge: 'POPULAR',
    rating: 4.9,
    studentCount: '5,000',
    mentorName: 'Meera Sen',
    mentorPhoto: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=100&q=80',
    language: 'English, Hindi, Bengali',
    certificate: true,
    emi: true,
    seatsLeft: 15,
    startsIn: '3 Days'
  },
  {
    id: 5,
    title: 'Career Counselling',
    target: 'Students & Professionals',
    duration: 'Per Session',
    mode: 'Online / Offline',
    center: 'All Centers',
    price: '₹199',
    originalPrice: '₹499',
    discount: '60% OFF',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80',
    description: 'Career mentor guiding students.',
    schedule: 'By Appointment',
    faculty: 'Certified Career Counsellors',
    syllabus: [
      'Career Roadmap Planning',
      'University Options Guidance',
      'Placement & Corporate Growth',
      'Personalized Assessment'
    ],
    enrollmentFee: '₹99',
    badge: '',
    rating: 4.9,
    studentCount: '1,200',
    mentorName: 'Vikram Singh',
    mentorPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&q=80',
    language: 'English, Hindi',
    certificate: false,
    emi: false,
    seatsLeft: 5,
    startsIn: 'Available Now'
  },
  {
    id: 6,
    title: 'Psychological Counselling',
    target: 'Students & Professionals',
    duration: 'Per Session',
    mode: 'Online / Offline',
    center: 'All Centers',
    price: '₹299',
    originalPrice: '₹699',
    discount: '57% OFF',
    image: 'https://images.unsplash.com/photo-1544027993-37dbfe43562a?auto=format&fit=crop&w=800&q=80',
    description: 'Professional counsellor helping students with stress management.',
    schedule: 'By Appointment',
    faculty: 'Expert Psychologists',
    syllabus: [
      'Stress & Anxiety Management',
      'Mental Wellness',
      'Motivation & Confidence Building',
      'Exam Preparation Mentality'
    ],
    enrollmentFee: '₹99',
    badge: 'SUPPORT',
    rating: 5.0,
    studentCount: '850',
    mentorName: 'Dr. Priya Roy',
    mentorPhoto: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=100&q=80',
    language: 'English, Bengali, Hindi',
    certificate: false,
    emi: false,
    seatsLeft: 2,
    startsIn: 'Available Now'
  }
];"""

content = re.sub(courses_pattern, new_courses, content, flags=re.DOTALL)
with open('src/App.jsx', 'w') as f:
    f.write(content)
